apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  hostPID: true
  containers:
  - name: ubuntu
    image: ubuntu:25.04
    command: ["sleep", "3600"]  # Keep pod alive for debugging
    securityContext:
      privileged: true  # Allows perf to attach to host processes
  # nodeName: kubeadm-01  # Replace with your node name, leave uncommented if you have 1 node
  restartPolicy: Never
  tolerations:  # Allow scheduling on control plane (tainted) nodes
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
