apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    # - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    # - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --kubeconfig=/var/lib/kubelet/kubeconfig
    - --leader-elect=false
    # - --bind-address=127.0.0.1
    - --cloud-provider=external
    - --service-cluster-ip-range=10.0.0.0/24
    # - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-name=kubernetes
    # - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    # - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    # - --controllers=*,bootstrapsigner,tokencleaner
    # - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/var/lib/kubelet/ca.crt
    - --service-account-private-key-file=/tmp/sa.key
    - --use-service-account-credentials=true
    - --v=2
    image: registry.k8s.io/kube-controller-manager:v1.30.14
    imagePullPolicy: IfNotPresent
    # livenessProbe:
    #   failureThreshold: 8
    #   httpGet:
    #     host: 127.0.0.1
    #     path: /healthz
    #     port: 10257
    #     scheme: HTTPS
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    #   timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    # startupProbe:
    #   failureThreshold: 24
    #   httpGet:
    #     host: 127.0.0.1
    #     path: /healthz
    #     port: 10257
    #     scheme: HTTPS
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    #   timeoutSeconds: 15
    volumeMounts:
    - mountPath: /tmp
      name: ca-certs
      readOnly: true
    - mountPath: /var/lib/kubelet
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /tmp
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /var/lib/kubelet
      type: DirectoryOrCreate
    name: kubeconfig
status: {}